# Generated by Django 4.2.1 on 2023-05-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_section_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='logos',
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_sections',
            field=models.ManyToManyField(blank=True, to='main.sub_section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(choices=[('about', 'About'), ('mining', 'Mining & Geology'), ('polar', 'Polar Expeditions'), ('photo', 'Photography'), ('translations', 'Translations'), ('contact', 'Contact')], max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='logos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.logo'),
        ),
    ]
