# Generated by Django 4.1.4 on 2023-05-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_section_logos_alter_section_sub_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='logos',
        ),
        migrations.AddField(
            model_name='section',
            name='logos',
            field=models.ManyToManyField(blank=True, to='main.logo'),
        ),
    ]
