# Generated by Django 4.2.1 on 2023-05-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sub_section_options_logo_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['weight']},
        ),
    ]
