# Generated by Django 4.2.1 on 2023-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_logo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(choices=[('about', 'About'), ('mining', 'Mining & Geology'), ('polar', 'Polar Expeditions'), ('photo', 'Photography'), ('translations', 'Translations'), ('contact', 'Contact'), ('impressum', 'Impressum'), ('legal', 'Data Protection')], max_length=50),
        ),
    ]
