# Generated by Django 4.2.1 on 2023-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title_de',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
